language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - nightly

matrix:
  include:
    - php: 5.3
      dist: precise
    # Test against dev dependencies
    - php: 7.1
      env: DEPS=dev

before_install:
  - if [ "$DEPS" = 'dev' ]; then perl -pi -e 's/^}$/,"minimum-stability":"dev"}/' composer.json; fi;

install:
  - composer install --no-progress

before_script:
  - export PATH=./vendor/bin:$PATH

script:
  - phpspec run -f pretty
  - behat -fprogress --strict
